### ISSUE TITLE
How can I delete your styles or change datepicker css files?

### ISSUE THREAD

**Issue by alipajand** [mehrabisajad/ng2-datepicker-jalali#2]
Thank you for your good module.
I want to change this style or overwrite it:
```
.ngb-dp-weekday[_ngcontent-c3], .ngb-dp-week-number[_ngcontent-c3] {
      line-height: 2rem;
}
```
How can I do that?

**Comment by mehrabisajad** [comment]
We don`t  use style in this repository.

I find this style in [src/datepicker/datepicker-month-view.ts](https://github.com/ng-bootstrap/ng-bootstrap/blob/26bc8df90eb0975c08f6d7592c387c3953849e9e/src/datepicker/datepicker-month-view.ts) bootstrap repository.
You should submit this issue to the `ng-bootstrap/ng-bootstrap` repository.

But I think you should develop Bootstrap itself. And manually fix this for yourself.
