### ISSUE TITLE
How to initial datepicker input with today date?

### ISSUE THREAD

**Issue by hadirsa** [mehrabisajad/ng2-datepicker-jalali#6]
I want to initialize `datepicker `input with current date. i use code below but is set it to Gregorian today date. 

` this.date = {year: now.getFullYear(), month: now.getMonth() + 1, day: now.getDate()};//result 2017/09/29
`
how can i initialize it to Jalali's today date?

I found `getToday()` in `ngb-calendar-persian.ts` but i cant use it.

**Comment by mehrabisajad** [comment]
You can get the current date like this:

https://github.com/mehrabisajad/ng2-datepicker-jalali-test/blob/master/src/app/app.component.ts#L22L32

**Comment by hadirsa** [comment]
@mehrabisajad yeah! the link was helpful! thanks.👍
