### ISSUE TITLE
change direction of component

### ISSUE THREAD

**Issue by AminAshtiani** [mehrabisajad/ng2-datepicker-jalali#7]
how to change direction of component to rtl? now for example "جمعه" is on the left and I want to change the direction to show "جمعه" on the right

**Comment by mehrabisajad** [comment]
You can use [ng2-datetimepicker-jalali](https://github.com/mehrabisajad/ng2-datetimepicker-jalali).
ng2-datetimepicker-jalali is a personalized datepicker using this component. Which includes date and time.

You can also use the rtl bootstrap.
