### ISSUE TITLE
Angular 7 Compatibility

### ISSUE THREAD

**Issue by Exlord** [mehrabisajad/ng2-datepicker-jalali#9]
ERROR in node_modules/ng2-datepicker-jalali/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service.d.ts(5,10): error TS2305: Module '"E:/www/emidox/front/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng2-datepicker-jalali/node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead.d.ts(3,10): error TS2305: Module '"E:/www/emidox/front/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Comment by mehrabisajad** [comment]
I added this library to Bootstrap. You can use it.
[https://ng-bootstrap.github.io/#/components/datepicker/calendars#jalali](https://ng-bootstrap.github.io/#/components/datepicker/calendars#jalali)
